/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.SwingUtilities;

/**
 *
 * @author voota
 */
public class JPanelMenu extends javax.swing.JPanel {

    /**
     * Creates new form ChucNang
     */
    public JPanelMenu() {
        initComponents();
        this.setSize(240,700);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelAvatar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        buttonSell = new javax.swing.JButton();
        buttonProduct = new javax.swing.JButton();
        buttonImport = new javax.swing.JButton();
        buttonSupplier = new javax.swing.JButton();
        buttonEmployee = new javax.swing.JButton();
        buttonCustomer = new javax.swing.JButton();
        buttonInvoice = new javax.swing.JButton();
        buttonAccount = new javax.swing.JButton();
        buttonDiscount = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        labelAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAvatar.setIcon(new javax.swing.ImageIcon("C:\\DoAn_Java\\src\\main\\java\\Icon\\avatar.png")); // NOI18N

        buttonSell.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\banHang.png")); // NOI18N
        buttonSell.setText("Bán hàng");
        buttonSell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSellMouseClicked(evt);
            }
        });
        buttonSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSellActionPerformed(evt);
            }
        });

        buttonProduct.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\quanLySanPham.png")); // NOI18N
        buttonProduct.setText("Quản lý sản phẩm");
        buttonProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonProductMouseClicked(evt);
            }
        });
        buttonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProductActionPerformed(evt);
            }
        });

        buttonImport.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\phieuNhap.png")); // NOI18N
        buttonImport.setText("Phiếu nhập");
        buttonImport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonImport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonImportMouseClicked(evt);
            }
        });
        buttonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportActionPerformed(evt);
            }
        });

        buttonSupplier.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\nhaCungCap.png")); // NOI18N
        buttonSupplier.setText("Nhà cung cấp");
        buttonSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonSupplier.setPreferredSize(new java.awt.Dimension(150, 23));
        buttonSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSupplierMouseClicked(evt);
            }
        });
        buttonSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupplierActionPerformed(evt);
            }
        });

        buttonEmployee.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\quanLyNhanVien.png")); // NOI18N
        buttonEmployee.setText("Quản lý nhân viên");
        buttonEmployee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEmployeeMouseClicked(evt);
            }
        });
        buttonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmployeeActionPerformed(evt);
            }
        });

        buttonCustomer.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\quanLyKhachHang.png")); // NOI18N
        buttonCustomer.setText("Quản lý khách hàng");
        buttonCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCustomerMouseClicked(evt);
            }
        });
        buttonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerActionPerformed(evt);
            }
        });

        buttonInvoice.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\quanLyHoaDon.png")); // NOI18N
        buttonInvoice.setText("Quản lý hóa đơn");
        buttonInvoice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonInvoiceMouseClicked(evt);
            }
        });
        buttonInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvoiceActionPerformed(evt);
            }
        });

        buttonAccount.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\quanLyTaiKhoan.png")); // NOI18N
        buttonAccount.setText("Tài khoản");
        buttonAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAccountMouseClicked(evt);
            }
        });
        buttonAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccountActionPerformed(evt);
            }
        });

        buttonDiscount.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\khuyenMai.png")); // NOI18N
        buttonDiscount.setText("Khuyến mãi");
        buttonDiscount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDiscountMouseClicked(evt);
            }
        });
        buttonDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiscountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonImport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonInvoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDiscount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSell, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSell, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonImport, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(labelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(labelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDiscountActionPerformed

    private void buttonSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSellActionPerformed
    }//GEN-LAST:event_buttonSellActionPerformed

    private void buttonProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonProductActionPerformed

    private void buttonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonImportActionPerformed

    private void buttonSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSupplierActionPerformed

    private void buttonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEmployeeActionPerformed

    private void buttonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomerActionPerformed

    private void buttonInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInvoiceActionPerformed

    private void buttonAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAccountActionPerformed

    private void buttonSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSellMouseClicked
        JPanelSell banHang = new JPanelSell();
        MainFrameGUI trangChu = (MainFrameGUI) SwingUtilities.getWindowAncestor(this);
        trangChu.getjPanelMain().removeAll();
        trangChu.getjPanelMain().add(banHang).setVisible(true);
        trangChu.pack();
    }//GEN-LAST:event_buttonSellMouseClicked

    private void buttonProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonProductMouseClicked
        JPanelProduct quanLySanPham = new JPanelProduct();
        MainFrameGUI trangChu = (MainFrameGUI) SwingUtilities.getWindowAncestor(this);
        trangChu.getjPanelMain().removeAll();
        trangChu.getjPanelMain().add(quanLySanPham).setVisible(true);
        trangChu.pack();
    }//GEN-LAST:event_buttonProductMouseClicked

    private void buttonImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonImportMouseClicked
        JPanelImport phieuNhap = new JPanelImport();
        MainFrameGUI trangChu = (MainFrameGUI) SwingUtilities.getWindowAncestor(this);
        trangChu.getjPanelMain().removeAll();
        trangChu.getjPanelMain().add(phieuNhap).setVisible(true);
        trangChu.pack();
    }//GEN-LAST:event_buttonImportMouseClicked

    private void buttonEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEmployeeMouseClicked
        JPanelEmployee quanLyNhanVien = new JPanelEmployee();
        MainFrameGUI mainFrame = (MainFrameGUI) SwingUtilities.getWindowAncestor(this);
        mainFrame.getjPanelMain().removeAll();
        mainFrame.getjPanelMain().add(quanLyNhanVien).setVisible(true);
        mainFrame.pack();
    }//GEN-LAST:event_buttonEmployeeMouseClicked

    private void buttonCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCustomerMouseClicked
        JPanelCustomer quanLyKhachHang = new JPanelCustomer();
        MainFrameGUI mainFrame = (MainFrameGUI) SwingUtilities.getWindowAncestor(this);
        mainFrame.getjPanelMain().removeAll();
        mainFrame.getjPanelMain().add(quanLyKhachHang).setVisible(true);
        mainFrame.pack();
    }//GEN-LAST:event_buttonCustomerMouseClicked

    private void buttonDiscountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDiscountMouseClicked
        JPanelDiscount khuyenMai = new JPanelDiscount();
        MainFrameGUI mainFrame = (MainFrameGUI) SwingUtilities.getWindowAncestor(this);
        mainFrame.getjPanelMain().removeAll();
        mainFrame.getjPanelMain().add(khuyenMai).setVisible(true);
        mainFrame.pack();
    }//GEN-LAST:event_buttonDiscountMouseClicked

    private void buttonAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAccountMouseClicked
        JPanelAccount taiKhoan = new JPanelAccount();
        MainFrameGUI mainFrame = (MainFrameGUI) SwingUtilities.getWindowAncestor(this);
        mainFrame.getjPanelMain().removeAll();
        mainFrame.getjPanelMain().add(taiKhoan).setVisible(true);
        mainFrame.pack();
    }//GEN-LAST:event_buttonAccountMouseClicked

    private void buttonInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonInvoiceMouseClicked
        JPanelInvoice hoaDon = new JPanelInvoice();
        MainFrameGUI mainFrame = (MainFrameGUI) SwingUtilities.getWindowAncestor(this);
        mainFrame.getjPanelMain().removeAll();
        mainFrame.getjPanelMain().add(hoaDon).setVisible(true);
        mainFrame.pack();
    }//GEN-LAST:event_buttonInvoiceMouseClicked

    private void buttonSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSupplierMouseClicked
        JPanelSupplier nhaCungCap = new JPanelSupplier();
        MainFrameGUI mainFrame = (MainFrameGUI) SwingUtilities.getWindowAncestor(this);
        mainFrame.getjPanelMain().removeAll();
        mainFrame.getjPanelMain().add(nhaCungCap).setVisible(true);
        mainFrame.pack();
    }//GEN-LAST:event_buttonSupplierMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAccount;
    private javax.swing.JButton buttonCustomer;
    private javax.swing.JButton buttonDiscount;
    private javax.swing.JButton buttonEmployee;
    private javax.swing.JButton buttonImport;
    private javax.swing.JButton buttonInvoice;
    private javax.swing.JButton buttonProduct;
    private javax.swing.JButton buttonSell;
    private javax.swing.JButton buttonSupplier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelAvatar;
    // End of variables declaration//GEN-END:variables
}
