/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import java.time.LocalDate;
import java.time.LocalDateTime;

import DTO.employeeDto;
import BUS.employeeBll;

/**
 *
 * @author voota
 */
public class JPanelEmployee extends javax.swing.JPanel {

    /**
     * Creates new form JPanelQuanLyNhanVien
     */
    public JPanelEmployee() {
    	
        initComponents();
        this.setSize(960,700);
        this.setVisible(true);
        loadEmployeeList();
    }
    employeeBll empBUS = new employeeBll();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldEmployeeId = new javax.swing.JTextField();
        textFieldEmployeeId.setEditable(false);
        textFieldEmployeeName = new javax.swing.JTextField();
        textFieldEmployeeDOB = new javax.swing.JTextField();
        textFieldEmployeeSalary = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonFix = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonShowAll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textFieldSearchEmployeeId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textFieldSearchEmployeeName = new javax.swing.JTextField();
        buttonSearchEmployee = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        scrollPane2 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
       
        jTable2.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO   Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
			      int row= jTable2.getSelectedRow();
			      if(row<0) {
			    	  return ;
			      }
			    String name=String.valueOf(jTable2.getValueAt(row, 1));
				String id=String .valueOf(jTable2.getValueAt(row,0));
				String DOB=String.valueOf(jTable2.getValueAt(row, 2));
				Double salary=(Double) jTable2.getValueAt(row,3);
				textFieldEmployeeId.setText(id);
				textFieldEmployeeName.setText(name);
				textFieldEmployeeDOB.setText(DOB);
				String numberString = String.valueOf(salary);
				textFieldEmployeeSalary.setText(numberString);
				System.out.println(id);
				
			}
		});

        jLabel2.setText("Mã nhân viên");

        jLabel3.setText("Họ và Tên");

        jLabel4.setText("Ngày sinh");

        jLabel6.setText("Lương");
        


        textFieldEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmployeeNameActionPerformed(evt);
            }
        });

        textFieldEmployeeDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmployeeDOBActionPerformed(evt);
            }
        });

        textFieldEmployeeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmployeeSalaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldEmployeeSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(textFieldEmployeeDOB)
                            .addComponent(textFieldEmployeeName, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldEmployeeId, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldEmployeeDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldEmployeeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
 
        
        buttonAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdd.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\them.png")); // NOI18N
        buttonAdd.setText("Thêm");
        buttonAdd.setBorderPainted(false);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	System.out.println(1);
            	try {
					if(
			    			textFieldEmployeeDOB.getText().trim().equals("") || 
			    			textFieldEmployeeName.getText().trim().equals("") || 
			    			textFieldEmployeeSalary.getText().trim().equals("")) 
					      
				JOptionPane.showMessageDialog(null,"Vui lòng nhập đủ thông tin");
					else {
						
						LocalDateTime currentDate = LocalDateTime.now();
						
						String dateString ="EMP"+"-"+currentDate+"";
						String employeeCode =dateString;
						employeeDto em = new employeeDto();
						em.setEmployeeID(employeeCode);
						em.setName(textFieldEmployeeName.getText());
						em.setDOB(textFieldEmployeeDOB.getText());
						double salary = Double.parseDouble(textFieldEmployeeSalary.getText());
						em.setSalary(salary);
						System.out.print(em);
						JOptionPane.showMessageDialog(null, empBUS.addEmployee(em));loadEmployeeList(); }
					 }catch (Exception ex) {
						JOptionPane.showMessageDialog(null,ex);
						JOptionPane.showMessageDialog(null,"sai");
					
				}
            }

			
        });

	
        buttonFix.setForeground(new java.awt.Color(255, 255, 255));
        buttonFix.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\sua.png")); // NOI18N
        buttonFix.setText("Sửa");
        buttonFix.setBorderPainted(false);
        buttonFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	try {
					if(
			    			textFieldEmployeeName.getText().trim().equals("") || 
			    			textFieldEmployeeDOB.getText().trim().equals("") || 
			    			textFieldEmployeeSalary.getText().trim().equals("")) 
					      
				JOptionPane.showMessageDialog(jPanel1,"Vui lòng nhập đủ thông tin trước khi sửa");
					else {
						
					
						String employeeCode =textFieldEmployeeId.getText();
						employeeDto em = new employeeDto();
						em.setEmployeeID(employeeCode);
						em.setName(textFieldEmployeeName.getText());
						em.setDOB(textFieldEmployeeDOB.getText());
					
						double salary = Double.parseDouble(textFieldEmployeeSalary.getText());
						em.setSalary(salary);
						System.out.print(em);
						JOptionPane.showMessageDialog(jPanel1, empBUS.fixEmployee(employeeCode, em));loadEmployeeList(); }
					}catch (Exception ex) {
						JOptionPane.showMessageDialog(jPanel1,ex);
						JOptionPane.showMessageDialog(jPanel1,"sai");
					
				}

				 
            }
        });

        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\xoa.png")); // NOI18N
        buttonDelete.setText("Xóa");
        buttonDelete.setBorderPainted(false);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	try {
					
				
						
					
						String employeeCode =textFieldEmployeeId.getText();
			
						JOptionPane.showMessageDialog(jPanel1, empBUS.deleteEmployee(employeeCode));loadEmployeeList(); }
            	catch (Exception ex) {
					JOptionPane.showMessageDialog(jPanel1,ex);
					JOptionPane.showMessageDialog(jPanel1,"sai");
					}
					
				}
           

			
        });

        buttonShowAll.setForeground(new java.awt.Color(255, 255, 255));
        buttonShowAll.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\xemTatCa.png")); // NOI18N
        buttonShowAll.setText("Làm mới");
        buttonShowAll.setBorderPainted(false);
        buttonShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	textFieldEmployeeId.setText("");
            	textFieldEmployeeDOB.setText("");
            	textFieldEmployeeName.setText("");
            	textFieldEmployeeSalary.setText("");
            	textFieldSearchEmployeeId.setText("");
            	textFieldSearchEmployeeName.setText("");
            	loadEmployeeList();
            }

			
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonShowAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonFix, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Image\\avatarNhanVien.png")); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tìm kiếm");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mã nhân viên");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        textFieldSearchEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSearchEmployeeIdActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldSearchEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 250, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Họ tên");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        textFieldSearchEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSearchEmployeeNameActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldSearchEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 250, 30));

        buttonSearchEmployee.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearchEmployee.setIcon(new javax.swing.ImageIcon("D:\\Cá Nhân\\Pictures\\Saved Pictures\\Icon\\timKiem.png")); // NOI18N
        buttonSearchEmployee.setText("Tìm kiếm");
        buttonSearchEmployee.setBorderPainted(false);
        buttonSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               if(textFieldSearchEmployeeId.getText().trim().equals("") || 
		    			textFieldSearchEmployeeName.getText().trim().equals("")) {
            	   JOptionPane.showMessageDialog(null,"Vui lòng nhập thông tin vào ô tìm kiếm mã nhân viên và họ tên");
               }else {
            	   ArrayList<employeeDto> arr = new ArrayList<employeeDto>();
            	   arr=empBUS.findAllEmployee(textFieldSearchEmployeeId.getText(),textFieldSearchEmployeeName.getText());
            	   if(arr!=null) {
            	   DefaultTableModel dtm = new DefaultTableModel();
            		dtm.addColumn("Mã nhân viên");
            		dtm.addColumn("Tên");
            		dtm.addColumn("Ngày sinh");
            		dtm.addColumn("Lương");
            		jTable2.setModel(dtm);
            		System.out.print(arr);
            		for(int i = 0; i < arr.size(); i++){
            			employeeDto em = arr.get(i);
            			String id =  em.getEmployeeID();
            			String name = em.getName();  
            			String DOB = em.getDOB();
            			Double salary= em.getSalary();
            			Object[] row = {id,name,DOB,salary};
            			dtm.addRow(row);
            		}
            	   }
            	   else{JOptionPane.showMessageDialog(null,"Không có nhân viên nào có mã và tên này");}
               }
            }
        });
        jPanel3.add(buttonSearchEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 150, 46));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Thông tin nhân viên");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ ", "Tên", "Ngày sinh", "Lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        scrollPane2.add(jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 47, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmployeeIdActionPerformed

    private void textFieldEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmployeeNameActionPerformed

    private void textFieldEmployeeDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmployeeDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmployeeDOBActionPerformed

    private void textFieldSearchEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSearchEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSearchEmployeeIdActionPerformed

    private void textFieldSearchEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSearchEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSearchEmployeeNameActionPerformed

    private void buttonSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchEmployeeActionPerformed

    private void textFieldEmployeeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmployeeSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmployeeSalaryActionPerformed

    private void buttonFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFixActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonFix;
    private javax.swing.JButton buttonSearchEmployee;
    private javax.swing.JButton buttonShowAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.awt.ScrollPane scrollPane2;
    private javax.swing.JTextField textFieldEmployeeDOB;
    private javax.swing.JTextField textFieldEmployeeId;
    private javax.swing.JTextField textFieldEmployeeName;
    private javax.swing.JTextField textFieldEmployeeSalary;
    private javax.swing.JTextField textFieldSearchEmployeeId;
    private javax.swing.JTextField textFieldSearchEmployeeName;
    // End of variables declaration//GEN-END:variables
    
    public void loadEmployeeList(){
 		DefaultTableModel dtm = new DefaultTableModel();
 		dtm.addColumn("Mã nhân viên");
 		dtm.addColumn("Tên");
 		dtm.addColumn("Ngày sinh");
 		dtm.addColumn("Lương");
 		jTable2.setModel(dtm);
 		ArrayList<employeeDto> arr = new ArrayList<employeeDto>();
 		arr = empBUS.getAllEmployees();         
 		for(int i = 0; i < arr.size(); i++){
 			employeeDto em = arr.get(i);
 			String id =  em.getEmployeeID();
 			String name = em.getName();  
 			String DOB = em.getDOB();
 			Double salary= em.getSalary();
 			Object[] row = {id,name,DOB,salary};
 			dtm.addRow(row);
 		}
 	}
}

